// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

//STAGING
// export const SUPABASE_URL="https://nesjuxdsjbtulcryvnjw.supabase.co";
// export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lc2p1eGRzamJ0dWxjcnl2bmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MDA2NTksImV4cCI6MjA3NzA3NjY1OX0.xJsQcG3CwYR2XspZv9NwA8x_Z1q8c_a_R5031hYqBzc";

//PRODUCTION
export const SUPABASE_URL="https://icwidsqbydgycuedhznc.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljd2lkc3FieWRneWN1ZWRoem5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzg4MDgsImV4cCI6MjA2NTgxNDgwOH0.kRaeJco9gDVBzWzeU9fOHjkXz4O0hmsie2b_Zu7U6Is"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);